name : github-actions-demo

on :
  push:
    branches : ["main"]

jobs :
  test :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v6
      - name : Setup Node.js
        uses : actions/setup-node@v6
        with :
          node-version : "22"
      - name : Install dependencies
        run : npm install
      - name : Start server
        run : npm start &
      - name : Run tests
        run : npm test
  deploy :
    needs : test
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v6
      - name : ssh into VM
        uses : appleboy/ssh-action@v0.1.5
        with :
          host : ${{ secrets.HOST_ADDRESS }}
          username : ${{ secrets.HOST_USER }}
          key : ${{ secrets.HOST_KEY }}
          script : |
            cd /home/claude/github-actions-demo
            git pull origin main
            npm install
            pm2 restart all